/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEventInitail,
  IEventInitailInterface,
} from "../../../contracts/IEventInitial.sol/IEventInitail";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "ts",
        type: "uint256",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IEventInitail__factory {
  static readonly abi = _abi;
  static createInterface(): IEventInitailInterface {
    return new utils.Interface(_abi) as IEventInitailInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEventInitail {
    return new Contract(address, _abi, signerOrProvider) as IEventInitail;
  }
}
